# Generated by Django 5.2.1 on 2025-06-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Maquinaria',
                'verbose_name_plural': 'Tipos de Maquinaria',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.SmallIntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinarias/')),
                ('precio_por_dia', models.FloatField()),
                ('stock_total', models.PositiveIntegerField(default=0)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('minimo', models.SmallIntegerField()),
                ('maximo', models.SmallIntegerField()),
                ('cantDias_total', models.SmallIntegerField()),
                ('cantDias_parcial', models.SmallIntegerField()),
                ('cantDias_nulo', models.SmallIntegerField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinarias', to='maquinarias.tipomaquinaria')),
            ],
        ),
    ]
