# Generated by Django 5.2.1 on 2025-06-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0001_initial'),
        ('usuarios', '0007_merge_20250530_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinariaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Total')),
                ('stock_disponible', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='maquinarias.maquinaria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='usuarios.sucursal')),
            ],
            options={
                'verbose_name': 'Stock de Maquinaria',
                'verbose_name_plural': 'Stocks de Maquinaria',
                'unique_together': {('maquinaria', 'sucursal')},
            },
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='sucursales',
            field=models.ManyToManyField(related_name='maquinarias', through='maquinarias.MaquinariaStock', to='usuarios.sucursal'),
        ),
    ]
