# Generated by Django 5.2.1 on 2025-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0002_maquinariastock_maquinaria_sucursales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinarias/images'),
        ),
    ]
