# Generated by Django 5.2.1 on 2025-07-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0004_maquinaria_es_placeholder'),
        ('maquinarias', '0004_maquinariafavorita'),
    ]

    operations = [
    ]
