# Generated by Django 5.2.1 on 2025-05-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_mail_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
