# Generated by Django 5.2.1 on 2025-05-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_2fa',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_2fa_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
