# Generated by Django 5.2.1 on 2025-05-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_token_2fa_usuario_token_2fa_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_2fa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_2fa_timestamp',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('EMPLEADO', 'Empleado'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=10, verbose_name='Tipo de usuario'),
        ),
    ]
