# Generated by Django 5.2.1 on 2025-05-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_2fa',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Token de verificación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_2fa_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp del token'),
        ),
    ]
