# Generated by Django 5.2.1 on 2025-05-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_sucursal_telefono'),
        ('usuarios', '0006_usuario_token_2fa_usuario_token_2fa_timestamp'),
    ]

    operations = [
    ]
