# Generated by Django 5.2.1 on 2025-06-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_20250530_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de recuperación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp del token de recuperación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_used',
            field=models.BooleanField(default=False, verbose_name='Token usado'),
        ),
    ]
