# Generated by Django 5.2.1 on 2025-07-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='calificacion',
            field=models.FloatField(default=5.0, help_text='Calificación del cliente en escala de 0.5 a 5 estrellas', verbose_name='Calificación del cliente'),
        ),
    ]
