# Generated by Django 5.2.1 on 2025-07-05 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_delete_reembolso'),
        ('usuarios', '0010_usuario_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(help_text='Calificación del cliente en escala de 0.5 a 5 estrellas', verbose_name='Calificación')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de calificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_cliente', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Calificación de cliente',
                'verbose_name_plural': 'Calificaciones de clientes',
                'ordering': ['-fecha_calificacion'],
            },
        ),
    ]
