# Generated by Django 5.2.1 on 2025-07-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_calificacioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='es_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
