# Generated by Django 5.2.1 on 2025-07-17 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_reserva_descuento_aplicado_and_more'),
        ('usuarios', '0012_sucursal_es_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO', 'Monto Fijo')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('usado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to=settings.AUTH_USER_MODEL)),
                ('reserva_uso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupon_aplicado', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
