# Generated by Django 5.2.1 on 2025-07-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='tipo',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje')], default='PORCENTAJE', max_length=10),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
