# Generated by Django 5.2.1 on 2025-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
