# Generated by Django 5.2.1 on 2025-06-19 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_codigo_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_reembolso', models.CharField(choices=[('TOTAL', 'Reembolso Total'), ('PARCIAL', 'Reembolso Parcial')], default='TOTAL', max_length=10)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado')], default='SOLICITADO', max_length=12)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('motivo_solicitud', models.TextField(help_text='Motivo de la solicitud de reembolso')),
                ('observaciones_admin', models.TextField(blank=True, help_text='Observaciones del administrador', null=True)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_procesados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reembolso', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
