# Generated by Django 5.2.1 on 2025-06-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reembolso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reembolso',
        ),
    ]
