# Generated by Django 5.2.1 on 2025-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_delete_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada'), ('NO_DEVUELTA', 'No Devuelta')], default='PENDIENTE_PAGO', max_length=15),
        ),
    ]
