# Generated by Django 5.2.1 on 2025-07-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_dni', models.CharField(max_length=20, verbose_name='DNI del cliente')),
                ('monto_reembolsado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto reembolsado')),
                ('fecha_reembolso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reembolso')),
                ('porcentaje_aplicado', models.IntegerField(verbose_name='Porcentaje de reembolso aplicado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='reservas.reserva', verbose_name='Reserva reembolsada')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-fecha_reembolso'],
            },
        ),
    ]
