# Generated by Django 5.2.1 on 2025-07-08 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reembolso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reembolso',
            options={},
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='cliente_dni',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='monto_reembolsado',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='porcentaje_aplicado',
        ),
        migrations.AddField(
            model_name='reembolso',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='dni_cliente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='fecha_reembolso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='reservas.reserva'),
        ),
    ]
