# Generated by Django 5.2.1 on 2025-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reembolso_options_remove_reembolso_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada'), ('NO_DEVUELTA', 'No Devuelta')], default='PENDIENTE_PAGO', max_length=15),
        ),
    ]
