# Generated by Django 5.2.1 on 2025-07-14 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reembolso_options_remove_reembolso_cliente_dni_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='reservas.reserva'),
        ),
    ]
