# Generated by Django 5.2.1 on 2025-07-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reembolso_cliente_alter_reembolso_reserva'),
        ('reservas', '0008_alter_reserva_estado'),
    ]

    operations = [
    ]
