# Generated by Django 5.2.1 on 2025-07-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_merge_20250715_2037'),
        ('reservas', '0009_merge_20250715_2244'),
    ]

    operations = [
    ]
